object Versions {
    const val kotlinPlugin = "1.7.0"
    const val gradlePlugin = "7.2.2"
    const val buildKonfig = "0.13.3"
    const val serializationPlugin = "1.7.10"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.5.0"
    const val material = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val viewModel = "2.5.1"
    const val ktor = "2.1.0"
    const val coroutines = "1.6.4"
    const val jUnit = "4.13.2"
    const val koin = "3.2.0"
}