object Versions {
    const val kotlin = "1.7.10"
    const val gradle = "7.2.2"
    const val buildKonfig = "0.13.3"
    const val coreKtx = "1.8.0"
    const val activityKtx = "1.5.1"
    const val viewModel = "2.5.1"
    const val ktor = "2.1.0"
    const val coroutines = "1.6.4"
    const val multiplatformSettings = "0.9"
    const val jUnit = "4.13.2"
    const val koin = "3.2.0"
    const val sqlDelight = "1.5.3"
    const val dateTime = "0.4.0"
    const val bigNum = "0.3.7"
    const val compose = "1.2.1"
    const val composeCompiler = "1.3.0"
    const val composeRuntime = "1.2.1"
    const val activityCompose = "1.5.1"
}