package com.paypay.currency_converter.utils

import com.ionspin.kotlin.bignum.decimal.RoundingMode
import com.ionspin.kotlin.bignum.decimal.toBigDecimal

class CurrencyUtils {
    data class CurrencyDescription(val en: String, val ja: String)

    companion object {
        fun calculateRate(currentRate: Double, selectedRate: Double, amount: Double): String {
            val calculatedRate = (currentRate / selectedRate) * amount
            return calculatedRate.toBigDecimal()
                .roundToDigitPositionAfterDecimalPoint(4, RoundingMode.CEILING)
                .toPlainString()
        }

        /**
         * KMM does not support per-language string array resources,
         * so one option is to store a list of currencies along with descriptions
         * for different languages programmatically.
         */
        val currencies = mapOf(
            "AED" to CurrencyDescription("United Arab Emirates Dirham", "アラブ首長国連邦ディルハム"),
            "AFN" to CurrencyDescription(" Afghan Afghani", "アフガニスタン アフガニ語"),
            "ALL" to CurrencyDescription("Albanian Lek", "アルバニアレク"),
            "AMD" to CurrencyDescription("Armenian Dram", "アルメニア ドラム"),
            "ANG" to CurrencyDescription("Netherlands Antillean Guilder", "オランダ領アンティルギルダー"),
            "AOA" to CurrencyDescription("Angolan Kwanza", "アンゴラクワンザ"),
            "ARS" to CurrencyDescription("Argentine Peso", "アルゼンチン ペソ"),
            "AUD" to CurrencyDescription("Australian Dollar", "オーストラリアドル"),
            "AWG" to CurrencyDescription("Aruban Florin", "アルバフロリン"),
            "AZN" to CurrencyDescription("Azerbaijani Manat", "アゼルバイジャンマナト"),
            "BAM" to CurrencyDescription(
                "Bosnia-Herzegovina Convertible Mark",
                "ボスニア・ヘルツェゴビナ兌換マルク"
            ),
            "BBD" to CurrencyDescription("Barbadian Dollar", "バルバドスドル"),
            "BDT" to CurrencyDescription("Bangladeshi Taka", "バングラデシュ・タカ"),
            "BGN" to CurrencyDescription("Bulgarian Lev", "ブルガリアレフ"),
            "BHD" to CurrencyDescription("Bahraini Dinar", "バーレーン ディナール"),
            "BIF" to CurrencyDescription("Burundian Franc", "ブルンジ フラン"),
            "BMD" to CurrencyDescription("Bermudan Dollar", "バミューダドル"),
            "BND" to CurrencyDescription("Brunei Dollar", "ブルネイドル"),
            "BOB" to CurrencyDescription("Bolivian Boliviano", "ボリビアのボリビアーノ"),
            "BRL" to CurrencyDescription("Brazilian Real", "ブラジル レアル"),
            "BSD" to CurrencyDescription("Bahamian Dollar", "バハマドル"),
            "BTC" to CurrencyDescription("Bitcoin", "ビットコイン"),
            "BTN" to CurrencyDescription("Bhutanese Ngultrum", "ブータンニュルタム"),
            "BWP" to CurrencyDescription("Botswanan Pula", "ボツワナ プラ"),
            "BYN" to CurrencyDescription("Belarusian Ruble", "ベラルーシ ルーブル"),
            "BZD" to CurrencyDescription("Belize Dollar", "ベリーズドル"),
            "CAD" to CurrencyDescription("Canadian Dollar", "カナダドル"),
            "CDF" to CurrencyDescription("Congolese Franc", "コンゴフラン"),
            "CHF" to CurrencyDescription("Swiss Franc", "スイスフラン"),
            "CLF" to CurrencyDescription("Chilean Unit of Account (UF)", "チリ会計単位 (UF)"),
            "CLP" to CurrencyDescription("Chilean Peso", "チリ ペソ"),
            "CNH" to CurrencyDescription("Chinese Yuan (Offshore)", "中国人民元 (オフショア)"),
            "CNY" to CurrencyDescription("Chinese Yuan", "中国元"),
            "COP" to CurrencyDescription("Colombian Peso", "コロンビア ペソ"),
            "CRC" to CurrencyDescription("Costa Rican Colón", "コスタリカのコロン"),
            "CUC" to CurrencyDescription("Cuban Convertible Peso", "キューバ兌換ペソ"),
            "CUP" to CurrencyDescription("Cuban Peso", "キューバ ペソ"),
            "CVE" to CurrencyDescription("Cape Verdean Escudo", "カーボベルデ エスクード"),
            "CZK" to CurrencyDescription("Czech Republic Koruna", "チェコ共和国コルナ"),
            "DJF" to CurrencyDescription("Djiboutian Franc", "ジブチ フラン"),
            "DKK" to CurrencyDescription("Danish Krone", "デンマーク クローネ"),
            "DOP" to CurrencyDescription("Dominican Peso", "ドミニカ ペソ"),
            "DZD" to CurrencyDescription("Algerian Dinar", "アルジェリア ディナール"),
            "EGP" to CurrencyDescription("Egyptian Pound", "エジプト ポンド"),
            "ERN" to CurrencyDescription("Eritrean Nakfa", "エリトリアのナクファ"),
            "ETB" to CurrencyDescription("Ethiopian Birr", "エチオピア ブル"),
            "EUR" to CurrencyDescription("Euro", "ユーロ"),
            "FJD" to CurrencyDescription("Fijian Dollar", "フィジードル"),
            "FKP" to CurrencyDescription("Falkland Islands Pound", "フォークランド諸島ポンド"),
            "GBP" to CurrencyDescription("British Pound Sterling", "英ポンド"),
            "GEL" to CurrencyDescription("Georgian Lari", "グルジア ラリ"),
            "GGP" to CurrencyDescription("Guernsey Pound", "ガーンジー ポンド"),
            "GHS" to CurrencyDescription("Ghanaian Cedi", "ガーナ セディ"),
            "GIP" to CurrencyDescription("Gibraltar Pound", "ジブラルタル ポンド"),
            "GMD" to CurrencyDescription("Gambian Dalasi", "ガンビア ダラシ"),
            "GNF" to CurrencyDescription("Guinean Franc", "ギニア フラン"),
            "GTQ" to CurrencyDescription("Guatemalan Quetzal", "グアテマラ ケツァル"),
            "GYD" to CurrencyDescription("Guyanaese Dollar", "ガイアナドル"),
            "HKD" to CurrencyDescription("Hong Kong Dollar", "香港ドル"),
            "HNL" to CurrencyDescription("Honduran Lempira", "ホンジュラスレンピラ"),
            "HRK" to CurrencyDescription("Croatian Kuna", "クロアチアクーナ"),
            "HTG" to CurrencyDescription("Haitian Gourde", "ハイチグールド"),
            "HUF" to CurrencyDescription("Hungarian Forint", "ハンガリー フォリント"),
            "IDR" to CurrencyDescription("Indonesian Rupiah", "インドネシアルピア"),
            "ILS" to CurrencyDescription("Israeli New Sheqel", "イスラエル新シェケル"),
            "IMP" to CurrencyDescription("Manx pound", "マンクスポンド"),
            "INR" to CurrencyDescription("Indian Rupee", "インドルピー"),
            "IQD" to CurrencyDescription("Iraqi Dinar", "イラクディナール"),
            "IRR" to CurrencyDescription("Iranian Rial", "イランのリアル"),
            "ISK" to CurrencyDescription("Icelandic Króna", "アイスランド クローナ"),
            "JEP" to CurrencyDescription("Jersey Pound", "ジャージー ポンド"),
            "JMD" to CurrencyDescription("Jamaican Dollar", "ジャマイカドル"),
            "JOD" to CurrencyDescription("Jordanian Dinar", "ヨルダン ディナール"),
            "JPY" to CurrencyDescription("Japanese Yen", "日本円"),
            "KES" to CurrencyDescription("Kenyan Shilling", "ケニア シリング"),
            "KGS" to CurrencyDescription("Kyrgystani Som", "キルギスタンソム"),
            "KHR" to CurrencyDescription("Cambodian Riel", "カンボジア リエル"),
            "KMF" to CurrencyDescription("Comorian Franc", "コモロ フラン"),
            "KPW" to CurrencyDescription("North Korean Won", "北朝鮮ウォン"),
            "KRW" to CurrencyDescription("South Korean Won", "韓国ウォン"),
            "KWD" to CurrencyDescription("Kuwaiti Dinar", "クウェート ディナール"),
            "KYD" to CurrencyDescription("Cayman Islands Dollar", "ケイマン諸島ドル"),
            "KZT" to CurrencyDescription("Kazakhstani Tenge", "カザフスタン テンゲ"),
            "LAK" to CurrencyDescription("Laotian Kip", "ラオスキップ"),
            "LBP" to CurrencyDescription("Lebanese Pound", "レバノン ポンド"),
            "LKR" to CurrencyDescription("Sri Lankan Rupee", "スリランカ ルピー"),
            "LRD" to CurrencyDescription("Liberian Dollar", "リベリアドル"),
            "LSL" to CurrencyDescription("Lesotho Loti", "レソトロティ"),
            "LYD" to CurrencyDescription("Libyan Dinar", "リビア ディナール"),
            "MAD" to CurrencyDescription("Moroccan Dirham", "モロッコディルハム"),
            "MDL" to CurrencyDescription("Moldovan Leu", "モルドバ レイ"),
            "MGA" to CurrencyDescription("Malagasy Ariary", "マダガスカル・アリアリ"),
            "MKD" to CurrencyDescription("Macedonian Denar", "マケドニア ディナール"),
            "MMK" to CurrencyDescription("Myanma Kyat", "ミャンマーチャット"),
            "MNT" to CurrencyDescription("Mongolian Tugrik", "モンゴルのトグログ語"),
            "MOP" to CurrencyDescription("Macanese Pataca", "マカオ パタカ"),
            "MRU" to CurrencyDescription("Mauritanian Ouguiya", "モーリタニア ウギア"),
            "MUR" to CurrencyDescription("Mauritian Rupee", "モーリシャスルピー"),
            "MVR" to CurrencyDescription("Maldivian Rufiyaa", "モルディブ ルフィア"),
            "MWK" to CurrencyDescription("Malawian Kwacha", "マラウイ クワチャ"),
            "MXN" to CurrencyDescription("Mexican Peso", "メキシコ ペソ"),
            "MYR" to CurrencyDescription("Malaysian Ringgit", "マレーシアリンギット"),
            "MZN" to CurrencyDescription("Mozambican Metical", "モザンビーク メティカル"),
            "NAD" to CurrencyDescription("Namibian Dollar", "ナミビアドル"),
            "NGN" to CurrencyDescription("Nigerian Naira", "ナイジェリア ナイラ"),
            "NIO" to CurrencyDescription("Nicaraguan Córdoba", "ニカラグア コルドバ"),
            "NOK" to CurrencyDescription("Norwegian Krone", "ノルウェークローネ"),
            "NPR" to CurrencyDescription("Nepalese Rupee", "ネパール ルピー"),
            "NZD" to CurrencyDescription("New Zealand Dollar", "ニュージーランドドル"),
            "OMR" to CurrencyDescription("Omani Rial", "オマーン リアル"),
            "PAB" to CurrencyDescription("Panamanian Balboa", "パナマバルボア"),
            "PEN" to CurrencyDescription("Peruvian Nuevo Sol", "ペルーのヌエボ・ソル"),
            "PGK" to CurrencyDescription("Papua New Guinean Kina", "パプア ニューギニア キナ"),
            "PHP" to CurrencyDescription("Philippine Peso", "フィリピンペソ"),
            "PKR" to CurrencyDescription("Pakistani Rupee", "パキスタン ルピー"),
            "PLN" to CurrencyDescription("Polish Zloty", "ポーランド ズウォティ"),
            "PYG" to CurrencyDescription("Paraguayan Guarani", "パラグアイのグアラニ語"),
            "QAR" to CurrencyDescription("Qatari Rial", "カタール リアル"),
            "RON" to CurrencyDescription("Romanian Leu", "ルーマニア レイ"),
            "RSD" to CurrencyDescription("Serbian Dinar", "セルビア ディナール"),
            "RUB" to CurrencyDescription("Russian Ruble", "ロシア ルーブル"),
            "RWF" to CurrencyDescription("Rwandan Franc", "ルワンダ フラン"),
            "SAR" to CurrencyDescription("Saudi Riyal", "サウジアラビア リヤル"),
            "SBD" to CurrencyDescription("Solomon Islands Dollar", "ソロモン諸島ドル"),
            "SCR" to CurrencyDescription("Seychellois Rupee", "セーシェル ルピー"),
            "SDG" to CurrencyDescription("Sudanese Pound", "スーダン ポンド"),
            "SEK" to CurrencyDescription("Swedish Krona", "スウェーデン クローナ"),
            "SGD" to CurrencyDescription("Singapore Dollar", "シンガポールドル"),
            "SHP" to CurrencyDescription("Saint Helena Pound", "セントヘレナ・ポンド"),
            "SLL" to CurrencyDescription("Sierra Leonean Leone", "シエラレオネ レオン"),
            "SOS" to CurrencyDescription("Somali Shilling", "ソマリア シリング"),
            "SRD" to CurrencyDescription("Surinamese Dollar", "スリナムドル"),
            "SSP" to CurrencyDescription("South Sudanese Pound", "南スーダン ポンド"),
            "STD" to CurrencyDescription(
                "São Tomé and Príncipe Dobra (pre-2018)",
                "サントメ・プリンシペ・ドブラ (2018年以前)"
            ),
            "STN" to CurrencyDescription("São Tomé and Príncipe Dobra", "サントメ・プリンシペ・ドブラ"),
            "SVC" to CurrencyDescription("Salvadoran Colón", "エルサルバドルコロン"),
            "SYP" to CurrencyDescription("Syrian Pound", "シリアポンド"),
            "SZL" to CurrencyDescription("Swazi Lilangeni", "スワジ・リランジェニ"),
            "THB" to CurrencyDescription("Thai Baht", "タイバーツ"),
            "TJS" to CurrencyDescription("Tajikistani Somoni", "タジキスタン ソモニ"),
            "TMT" to CurrencyDescription("Turkmenistani Manat", "トルクメニスタンマナト"),
            "TND" to CurrencyDescription("Tunisian Dinar", "チュニジア ディナール"),
            "TOP" to CurrencyDescription("Tongan Pa'anga", "トンガ・パアンガ"),
            "TRY" to CurrencyDescription("Turkish Lira", "トルコ リラ"),
            "TTD" to CurrencyDescription("Trinidad and Tobago Dollar", "トリニダード・トバゴドル"),
            "TWD" to CurrencyDescription("New Taiwan Dollar", "ニュー台湾ドル"),
            "TZS" to CurrencyDescription("Tanzanian Shilling", "タンザニア シリング"),
            "UAH" to CurrencyDescription("Ukrainian Hryvnia", "ウクライナ・グリブナ"),
            "UGX" to CurrencyDescription("Ugandan Shilling", "ウガンダ シリング"),
            "USD" to CurrencyDescription("United States Dollar", "米ドル"),
            "UYU" to CurrencyDescription("Uruguayan Peso", "ウルグアイ ペソ"),
            "UZS" to CurrencyDescription("Uzbekistan Som", "ウズベキスタン ソム"),
            "VEF" to CurrencyDescription("Venezuelan Bolívar Fuerte (Old)", "ベネズエラ ボリバル フエルテ (旧)"),
            "VES" to CurrencyDescription("Venezuelan Bolívar Soberano", "ベネズエラのボリバル・ソベラノ"),
            "VND" to CurrencyDescription("Vietnamese Dong", "ベトナムドン"),
            "VUV" to CurrencyDescription("Vanuatu Vatu", "バヌアツ バツ"),
            "WST" to CurrencyDescription("Samoan Tala", "サモア タラ"),
            "XAF" to CurrencyDescription("CFA Franc BEAC", "CFAフランBEAC"),
            "XAG" to CurrencyDescription("Silver Ounce", "シルバーオンス"),
            "XAU" to CurrencyDescription("Gold Ounce", "金オンス"),
            "XCD" to CurrencyDescription("East Caribbean Dollar", "東カリブドル"),
            "XDR" to CurrencyDescription("Special Drawing Rights", "特別引出権"),
            "XOF" to CurrencyDescription("CFA Franc BCEAO", "CFA フラン BCEAO"),
            "XPD" to CurrencyDescription("Palladium Ounce", "パラジウムオンス"),
            "XPF" to CurrencyDescription("CFP Franc", "CFP フラン"),
            "XPT" to CurrencyDescription("Platinum Ounce", "プラチナオンス"),
            "YER" to CurrencyDescription("Yemeni Rial", "イエメン リアル"),
            "ZAR" to CurrencyDescription("South African Rand", "南アフリカランド"),
            "ZMW" to CurrencyDescription("Zambian Kwacha", "ザンビア クワチャ"),
            "ZWL" to CurrencyDescription("Zimbabwean Dollar", "ジンバブエドル"),
        )
    }
}